### ISSUE TITLE
Performetrics.monitorOperation not returning MonitoredRunnable after an exception

### ISSUE THREAD

**Issue by LeonardoSoaresDev** [oswaldobapvicjr/performetrics#83]
**Describe the bug**
The class Performetrics has a method called "monitorOperation" that executes the runnable that is passed as parameter,
when the runnable throws an exception the monitorOperation method does not return a MonitoredRunnable object, then the time execution cannot be calculated.

**To Reproduce**
Provide a runnable to the monitorOperation method that throws an exception.

**Expected behavior**
Return the MonitoredRunnable object even when an exception is being throw.

**Screenshots**
N/A

**Desktop**
N/A

**Additional context**
N/A

**Comment by oswaldobapvicjr** [comment]
Solved by #84
